spring:
  # 使用 Springboot 默认的 HikariCP 连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lyuanzhi.com:3306/OxceanDB?serverTimezone=GMT
    username: root
    password: Eshxcpqw.123
    hikari:
      maxLifetime: 40000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 4 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)硬盘数
